[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
cmd = "mkdir -p /var/log"

[phases.install]
cmd = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"

[phases.build]
cmd = "php artisan config:cache && php artisan route:cache && php artisan view:cache"

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"