services:
  - type: web
    name: phisyomarv2
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan db:seed --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: PhisyoMar
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: phisyomarv2
          property: url
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: phisyomarv2-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: phisyomarv2-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: phisyomarv2-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: phisyomarv2-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: phisyomarv2-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: log
      - key: BCRYPT_ROUNDS
        value: 12

  - type: pserv
    name: phisyomarv2-db
    env: mysql
    database: phisyomarv2
    user: phisyomarv2
    ipAllowList: []